use_frameworks!

platform :ios, '9.0'

target 'xkt_componentization_Example' do
  pod 'xkt_componentization', :path => '../'

  target 'xkt_componentization_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
